// import 'react-datalist-input/dist/styles.css';
// import DataListInput from 'react-datalist-input';
import Footer from '../components/Footer';
import Head from 'next/head';
import Header from '../components/Header';
import { InfoTab } from '@impulsogov/design-system';
// import { data } from '../municipios';
// import { v1 as generateUUID } from 'uuid';

export default function Home() {
  // const getDataListItems = () => data.map(({ nome, uf }) => ({
  //   id: generateUUID(),
  //   value: `${nome}, ${uf}`
  // }));

  return (
    <>
      <Head>
        <title>Desafio Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='w-full'>

        <InfoTab
          contentList={ [
            {
              buttonLink: '/',
              buttonTitle: 'SOBRE SAÚDE MENTAL',
              leftTitle: 'Saúde Mental',
              rightContent: `
                Uma plataforma gratuita, que utiliza bases de dados 
                públicas para auxiliar na gestão dos serviços de saúde mental 
                do município. Conheça mais sobre o trabalho realizado pela 
                Impulso em parceria com o Instituto Cactus e o município de 
                Aracaju (SE).
              `,
              rightTitle: 'O que é a plataforma de indicadoresdeSaúde Mental?'
            },
            {
              buttonLink: '/',
              buttonTitle: 'entenda',
              leftTitle: 'Glossário',
              rightContent: `
                Acesse um siglário e a ficha técnica de nossos 
                indicadores para compreender como eles são calculados, quais 
                são as bases de dados que os alimentam, com qual periodicidade 
                eles são atualizados e muito mais
              `,
              rightTitle: 'Entenda como interpretar os indicadores'
            }
          ] }
        />

        {/* <DataListInput
          label="Escolha um município"
          placeholder="Porto Alegre, RS"
          items={getDataListItems()}
          onSelect={(item) => console.log(item.value)}
        /> */}

      </main>

      <Footer />
    </>
  );
}
