import Footer from '../components/Footer';
import Head from 'next/head';
import Header from '../components/Header';
import { InfoTab } from '@impulsogov/design-system';
import Modal from '../components/Modal';
import { useState } from 'react';

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const openModal = () => setIsModalOpen(true);

  const closeModal = () => setIsModalOpen(false);

  return (
    <>
      <Head>
        <title>Desafio Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header onLogoClick={openModal} />

      <main className='w-full'>
        <InfoTab
          contentList={ [
            {
              buttonLink: '/',
              buttonTitle: 'SOBRE SAÚDE MENTAL',
              leftTitle: 'Saúde Mental',
              rightContent: `
                Uma plataforma gratuita, que utiliza bases de dados 
                públicas para auxiliar na gestão dos serviços de saúde mental 
                do município. Conheça mais sobre o trabalho realizado pela 
                Impulso em parceria com o Instituto Cactus e o município de 
                Aracaju (SE).
              `,
              rightTitle: 'O que é a plataforma de indicadores de Saúde Mental?'
            },
            {
              buttonLink: '/',
              buttonTitle: 'entenda',
              leftTitle: 'Glossário',
              rightContent: `
                Acesse um siglário e a ficha técnica de nossos 
                indicadores para compreender como eles são calculados, quais 
                são as bases de dados que os alimentam, com qual periodicidade 
                eles são atualizados e muito mais
              `,
              rightTitle: 'Entenda como interpretar os indicadores'
            }
          ] }
        />

        {isModalOpen && <Modal onCloseBtnClick={closeModal} />}
      </main>

      <Footer />
    </>
  );
}
